### PR TITLE
fix: rework heartbeats and periodic reinforcements for reliability

### LINKED ISSUE #796: Agent periodic enforcer is never triggered
Periodic enforcer is never called right now b/c it's timer is being reset on each heartbeat which is happening more often.

### PR DESCRIPTION
**Pull request by Frostman**
Fixes #796

### CODE REVIEW

File: pkg/agent/agent.go [hunk 1]
```diff
@@ -402,68 +422,60 @@ func (svc *Service) processAgent(ctx context.Context, agent *agentapi.Agent, rea
...
-
-	if !enforce && agent.Generation == *currentGen {
+func (svc *Service) processAgentFromKube(ctx context.Context, kube client.Client, agent *agentapi.Agent, currentGen *int64) error {
+	if agent.Generation == *currentGen {
 		return nil
 	}
 
 	start := time.Now()
 
 	if agent.Generation != *currentGen {
```
Comment (edipascale) [inline pkg/agent/agent.go:438]: this condition is always true now

**Review by edipascale — DISMISSED** [review]
