### PR TITLE
Fixes for external routing

### LINKED ISSUE #1175: Peering two VPCs to an external via the gateway makes them able to ping each other
tested on env-5 - we could not really test this on VMs due to ACLs not working there.

setup:
```
core@control-1 ~ $ k get peer
NAME              AGE
vpc-05--default   92s
vpc-06--default   92s
core@control-1 ~ $ k get vpcattach
NAME                                                VPCSUBNET          CONNECTION                       NATIVEVLAN   AGE
server-2--bundled--ds5000-01--vpc-01--subnet-01     vpc-01/subnet-01   server-2--bundled--ds5000-01                  3m50s
server-3--unbundled--ds5000-02--vpc-02--subnet-01   vpc-02/subnet-01   server-3--unbundled--ds5000-02                3m50s
server-4--unbundled--ds5000-02--vpc-03--subnet-01   vpc-03/subnet-01   server-4--unbundled--ds5000-02                3m50s
server-5--unbundled--ds5000-02--vpc-04--subnet-01   vpc-04/subnet-01   server-5--unbundled--ds5000-02                3m50s
server-6--bundled--ds3000-05--vpc-05--subnet-01     vpc-05/subnet-01   server-6--bundled--ds3000-05                  3m50s
server-7--unbundled--ds3000-06--vpc-06--subnet-01   vpc-06/subnet-01   server-7--unbundled--ds3000-06                3m50s
core@control-1 ~ $ k get externalpeering
NAME              VPC      EXTERNAL   AGE
vpc-01--default   vpc-01   default    2m15s
vpc-03--default   vpc-03   default    2m15s
```

test:
```
02:01:52 ERR Test connectivity failed ping=2 iperf=0 curl=0 took=10.740640731s errors="ping server-7 -> server-6: should not be reachable but ping succeeded (sent 5, rcvd 5, expected false)\nping server-6 -> server-7: should not be reachable but ping succeeded (sent 5, rcvd 5, expected false)"
02:01:52 ERR test-connectivity: ping server-7 -> server-6: should not be reachable but ping succeeded (sent 5, rcvd 5, expected false)
ping server-6 -> server-7: should not be reachable but ping succeeded (sent 5, rcvd 5, expected false)
```

### PR DESCRIPTION
**Pull request by edipascale**
Fixes #1175

### CODE REVIEW

File: pkg/agent/dozer/bcm/plan.go [hunk 1]
```diff
@@ -883,6 +883,34 @@ func planExternals(agent *agentapi.Agent, spec *dozer.Spec) error {
...
+					},
+					Result: dozer.SpecRouteMapResultAccept,
+				},
+			},
+		}
+
+		aclName := ipNsNoExtPeeringACLName(ipnsName)
+		entries := map[uint32]*dozer.SpecACLEntry{}
+		for idx, subnet := range ipns.Subnets {
+			entries[uint32(idx+1)] = &dozer.SpecACLEntry{ //nolint:gosec
```
Comment (Frostman) [inline pkg/agent/dozer/bcm/plan.go]: Generally, we're trying to avoid situations where adding another subnet at the beginning of the IPNS subnet list would cause all entries to be rewritten. The Catalog's subnetIDs should be used instead. We already allocate IDs for some things like VPC subnets, etc, so please just add IPNS subnets to it as well (`subnetsReq` in agent ctrl).
